[project]
name = "data-financial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dask[array,distributed]>=2025.11.0",
    "duckdb>=1.4.2",
    "pandas>=2.3.3",
    "pyarrow>=22.0.0",
]
